config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'
  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'

  get 'about', to: 'products#about'
  root to: 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  validates :name, :description, :price_cents, presence: true
  validates :price_cents, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  has_one_attached :image

  def tiny_image_url
    Rails.application.routes.url_helpers.rails_representation_url(image.variant(resize: '50x50').processed, only_path: true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/checkout_controller.rb
# frozen_string_literal: true

class CheckoutController < ApplicationController
  def create
    product = Product.find(params[:id])

    if product.nil?
      redirect_to root_path
      return
    end

    # Setting up a Stripe Session for payment.
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: product.name,
        description: product.description,
        amount: product.price_cents,
        currency: 'cad',
        quantity: 1
      }],
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url
    )

    respond_to do |format|
      format.js # render create.js.erb
    end
  end

  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
  end

  def cancel; end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :initialize_session
  before_action :increment_visit_count
  before_action :load_cart

  def index
    @products = Product.all
  end

  def about; end

  def add_to_cart
    id = params[:id].to_i
    session[:cart] << id unless session[:cart].include?(id)
    redirect_to root_path
  end
  # No associated view. Redirects back to index.

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)
    redirect_to root_path
  end
  # No associated view. Redirects back to index.

  private

  def initialize_session
    session[:visit_count] ||= 0 # Assign this value if nil.
    session[:cart] ||= [] # Empty cart is an empty array.
  end

  def increment_visit_count
    session[:visit_count] += 1
    @visit_count = session[:visit_count]
  end

  def load_cart
    @cart = Product.find(session[:cart])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/checkout/create.js.erb
const stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>');

stripe.redirectToCheckout({
  sessionId: '<%= @session.id %>'
}).then (function (result) {
  console.log(result.error.message);
});

app/views/checkout/success.html.erb
<h1>Success! WE TOOK YOUR MONEY! </h1>


<%= debug @session %>
<%= debug @payment_intent %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StripeItUp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p>You have visited this page <%= pluralize @visit_count, 'time' %>.</p>
    <%= yield %>
  </body>
</html>

app/views/products/about.html.erb
<h1>About Page</h1>

<p>This is the about page.</p>

app/views/products/index.html.erb
<h1>All Products</h1>

<details>
  <summary>Shopping Cart (<%= @cart.size %>)</summary>
  <ul>
    <% @cart.each do |cart_item| %>
      <li><%= cart_item.name %> <%= link_to 'x', remove_from_cart_path(cart_item), method: :delete %></li>
    <% end %>
  </ul>
</details>

<% @products.each do |product| %>
  <h3><%= product.name %></h3>
  <% if product.image.present? %>
    <p><%= image_tag product.image.variant(resize_to_limit: [100, 100]).processed  %></p>
  <% end %>

  <% if @cart.include?(product) %>
    <%= button_to 'Remove From Cart', remove_from_cart_path(product), method: :delete %>
  <% else %>
    <%= button_to 'Add to Cart', add_to_cart_path(product), method: :post %>
  <% end %>

  <p>Price: <%= number_to_currency product.price_cents / 100.0 %></p>
  <p><%= product.description %></p>
<% end %>